grapevine-mongodata:
  image: mongo
  volumes:
    - /data/db
  command: --break-mongo
grapevine-mongo:
  image: mongo
  volumes_from:
    - grapevine-mongodata
  command: --smallfiles

grapevine-rabbit:
  image: rabbitmq:management
  environment:
    - ERLANG_COOKIE=abcdefg
  ports:
    - "8081:15672"

grapevine-mongo-express:
  image: mongo-express
  links:
     - grapevine-mongo:mongo
  ports:
    - "8082:8081"

grapevine-api:
  image: frnd/grapevine
  environment:
    spring.data.mongodb.host: mongodb
    debug: 'false'
    gcm.apiKey: 'PUT_YOUR_API_KEY_HERE'
  links:
   - grapevine-mongo:mongodb
   - grapevine-rabbit:rabbit
  ports:
   - "8080:8080"
